-- ============================================================
-- Hive Task OS — Seed Data
-- Run AFTER supabase-schema.sql in the Supabase SQL Editor.
--
-- No demo data is seeded. Users sign up and create their own
-- projects, tasks, channels, and contacts from scratch.
-- ============================================================
